### ISSUE TITLE
安装完就这样了eee

### ISSUE THREAD

**Issue by NeeeeeeeBs** [JOYACEpoor/LoliconMirai#5]
这这这....

Request{method=GET, url=https://api.lolicon.app/setu/v2?r18=2&proxy=i.pixiv.re&num=5&tag=}
2023-02-26 22:18:22 W/nya.xfy.LoliconMirai: Exception in executing command `[mirai:source:ids=[10738], internalIds=[1817969751], from group xxx to xxxx at 1677421100]/random`
 command owned by nya.xfy.LoliconMirai v1.6.5 with NormalMember(xxx)
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 285: Encountered an unknown key 'aiType' at path: $.data[0].ext
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: .....","女体美","此女体美哉"],"ext":"png","aiType":0,"uploadDate":1660057.....
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:528)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.failOnUnknownKey(AbstractJsonLexer.kt:523)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.handleUnknown(StreamingJsonDecoder.kt:201)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:187)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:121)
        at LoliconMirai-1.6.5.jar//nya.xfy.utils.LoliconResponse$Data$$serializer.deserialize(LoliconResponse.kt:5)
        at LoliconMirai-1.6.5.jar//nya.xfy.utils.LoliconResponse$Data$$serializer.deserialize(LoliconResponse.kt:5)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:38)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:111)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:537)
        at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:38)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:111)
        at LoliconMirai-1.6.5.jar//nya.xfy.utils.LoliconResponse$$serializer.deserialize(LoliconResponse.kt:3)
        at LoliconMirai-1.6.5.jar//nya.xfy.utils.LoliconResponse$$serializer.deserialize(LoliconResponse.kt:3)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:38)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
        at LoliconMirai-1.6.5.jar//nya.xfy.utils.Handler.handle(Handler.kt:90)
        at LoliconMirai-1.6.5.jar//nya.xfy.utils.Handler.handle$default(Handler.kt:33)
        at LoliconMirai-1.6.5.jar//nya.xfy.commands.Getter.handle(Getter.kt:14)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:337)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:125)
        at chat-command-0.6.0.mirai.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:98)
        at chat-command-0.6.0.mirai.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:66)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        **at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)**

**Comment by JOYACEpoor** [comment]
hi，由于很久没有进行维护更新，api的返回的json对象更新了而我没有更新插件的json解析导致现在会报错无法正常使用，过几天我更新一下吧\\

**Comment by JOYACEpoor** [comment]
https://github.com/JOYACEpoor/LoliconMirai/releases/tag/v1.6.6

**Comment by JOYACEpoor** [comment]
摆烂了好久，不知道有没有动过别的地方！！期待反馈

**Comment by NeeeeeeeBs** [comment]
**还是炸了qwq**
0m2023-03-08 14:37:07 V/Bot.2695743645: [NINE PERCENT(1094644576)] () -> /random[0m[m
[92m2023-03-08 14:37:08 I/nya.xfy.LoliconMirai: 解析中[m
Request{method=GET, url=https://api.lolicon.app/setu/v2?r18=2&proxy=i.pixiv.re&num=6&tag=}[0m[m
[93m2023-03-08 14:37:08 W/nya.xfy.LoliconMirai: Exception in executing command `[mirai:source:ids=[12678], internalIds=[727840022], from group  to  at ]/random`[m
 command owned by nya.xfy.LoliconMirai v1.6.6 with NormalMember(1055219589)[m
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 234: Expected quotation mark '"', but had '0' instead at path: $.data[0].aiType[m
JSON input: .....","子宫口"],"ext":"jpg","aiType":0,"uploadDate":1621924428000,".....[m
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)[m
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)[m
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:528)[m
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:526)[m
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:224)[m
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:207)[m
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:74)[m
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeKeyString(StringJsonLexer.kt:85)[m
	at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeString(AbstractJsonLexer.kt:313)[m
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(StreamingJsonDecoder.kt:292)[m
	at kotlinx.serialization.encoding.AbstractDecoder.decodeStringElement(AbstractDecoder.kt:58)[m
	at LoliconMirai-1.6.6.jar//nya.xfy.utils.LoliconResponse$Data$$serializer.deserialize(LoliconResponse.kt:5)[m
	at LoliconMirai-1.6.6.jar//nya.xfy.utils.LoliconResponse$Data$$serializer.deserialize(LoliconResponse.kt:5)[m
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)[m
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:38)[m
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)[m
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)[m
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:111)[m
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:537)[m
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)[m
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)[m
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)[m
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)[m
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)[m
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:38)[m
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)[m
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)[m
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:111)[m
	at LoliconMirai-1.6.6.jar//nya.xfy.utils.LoliconResponse$$serializer.deserialize(LoliconResponse.kt:3)[m
	at LoliconMirai-1.6.6.jar//nya.xfy.utils.LoliconResponse$$serializer.deserialize(LoliconResponse.kt:3)[m
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)[m
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:38)[m
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)[m
	at LoliconMirai-1.6.6.jar//nya.xfy.utils.Handler.handle(Handler.kt:120)[m
	at LoliconMirai-1.6.6.jar//nya.xfy.utils.Handler.handle$default(Handler.kt:39)[m
	at LoliconMirai-1.6.6.jar//nya.xfy.commands.Getter.handle(Getter.kt:17)[m
	at LoliconMirai-1.6.6.jar//nya.xfy.commands.Getter.handle$default(Getter.kt:15)[m
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[m
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[m
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[m
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)[m
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)[m
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)[m
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)[m
	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)[m
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:337)[m
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)[m
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)[m
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)[m
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)[m
	at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)[m
	at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)[m
	at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)[m
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)[m
	at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:125)[m
	at chat-command-0.6.0.mirai.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:98)[m
	at chat-command-0.6.0.mirai.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:66)[m
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)[m
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)[m
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)[m
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)[m
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)[m
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)[m
[0m[m
[0m2023-03-08 14:37:20 V/Bot.2INE PERCENT(1094644576)] 陈/keyword 蒂法[0m[m

**Comment by JOYACEpoor** [comment]
再次更新了v1.6.6prerelease，这次测试过了！

**Comment by JOYACEpoor** [comment]
尴尬了 试试https://github.com/JOYACEpoor/LoliconMirai/releases/tag/v2.0.0吧

**Comment by NeeeeeeeBs** [comment]
成功啦！

**Comment by NeeeeeeeBs** [comment]
获取色图时发生异常: java.net.NoRouteToHostException: No route to host (Host unreachable)
啊这，启动了玩了一会就炸了，重启后又能用了。然后玩一会又炸，然后又要重启。
